### ISSUE TITLE
代码缺失

### ISSUE THREAD

**Issue by CocaColaKing** [gomate-community/GoMate#20]
你好，代码下载下来跑不起来，看上去是缺少了一些，是还没有实现吗？

![image](https://github.com/gomate-community/GoMate/assets/18070309/36397a96-9027-4c25-91a8-30e0729f9d4b)

**Comment by yanqiangmiffy** [comment]
@CocaColaKing 嗯嗯，目前版本不太稳定，您可以加我微信，到时候我实现好了和你说下
1185918903
