### ISSUE TITLE
项目文件结构都不对，咋用啊，多个文件的导包，无法导入

### ISSUE THREAD

**Issue by xsoway** [gomate-community/GoMate#23]
<img width="1143" alt="image" src="https://github.com/gomate-community/GoMate/assets/139938648/f7bf46ca-d9d2-4904-bd0e-180d1486e6a7">

**Comment by yanqiangmiffy** [comment]
你好，目前有些模块没有对齐，正在离线重构，您可以加我微信1185918903，完善好了，通知您
