### ISSUE TITLE
cannot import name 'HyDE_rewriter' from 'gomate.modules'

### ISSUE THREAD

**Issue by weirdo2310** [gomate-community/GoMate#27]
![image](https://github.com/gomate-community/GoMate/assets/66229572/6c9a6540-0344-4dca-83da-f027fe44b42b)

**Comment by yanqiangmiffy** [comment]
您好，目前最新代码还有同步，稍等，我把例子同步一下

**Comment by yanqiangmiffy** [comment]
可加微信1185918903

**Comment by yanqiangmiffy** [comment]
已修复
