### ISSUE TITLE
bm25检索输入query应该是列表

### ISSUE THREAD

**Issue by l99500** [gomate-community/GoMate#30]
https://github.com/gomate-community/GoMate/blob/b750d2dcc8c1dd6fe14d730e22a8b9abcf46b10a/gomate/modules/retrieval/bm25_retriever.py#L267C9-L267C58

应该修改为 self.tokenizer(query)

**Comment by yanqiangmiffy** [comment]
好的，重构后会同步，目前离线索引还不支持
