### ISSUE TITLE
signal 11:SIGSEGV

### ISSUE THREAD

**Issue by wangchao1241503759** [gomate-community/GoMate#42]
运行app.py，启动不起来，什么情况，模块加载好些异常
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/8cbfd740-5b06-4916-8a35-00ea246b0f5d">

**Comment by yanqiangmiffy** [comment]
你好，电脑是否支持GPU呢？看起是来是内存不足了；另外你这里是debug模式运行吧，需要右键run运行

**Comment by wangchao1241503759** [comment]
> 你好，电脑是否支持GPU呢？看起是来是内存不足了；另外你这里是debug模式运行吧，需要右键run运行

1、目前不支持GPU呢，必须GPU模式么？
2、run运行也是一样的，一样的错误，后改用debug想分析问题原因，查了下也是内存问题
咱们这个有内存要求么？什么配置合适？感谢
