### ISSUE TITLE
import datrie ModuleNotFoundError: No module named 'datrie'

### ISSUE THREAD

**Issue by cristianohello** [gomate-community/GoMate#70]
GoMate-main\gomate\modules\document\rag_tokenizer.py", line 19, in <module>

这个脚本从哪找的？
    import datrie
ModuleNotFoundError: No module named 'datrie'

这个datrie干啥的？

**Comment by yanqiangmiffy** [comment]
`pip install datrie`

是用来加载huqie此表的

**Comment by cristianohello** [comment]
@yanqiangmiffy 
能不用这个嘛？怎么注释掉
